fastlane_version '2.133.0'

before_all do
  ensure_git_branch
  # ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
end

platform :android do
  desc 'Build the Android application.'
  lane :build do
    # gradle(task: 'clean', project_dir: 'android/')

    gradle(task: 'assemble', build_type: 'Debug', project_dir: 'android/', flavor: 'MegafonoApp')
    gradle(task: 'assemble', build_type: 'Debug', project_dir: 'android/', flavor: 'DukeApp')
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
  end
end